%YAML 1.2
--- # profile for Navapp with replication
# 1 CatalogMT as master node
# 1 CatalogWeb as replica node
# shared sdp
# no mcom

# profile handler
adapter: ???

# profile identifier
id: navapp-and-mcom

# instance parameters and their keys in the profile
instance:
    navapp: CATALOG_WEB_BUILD
    mcom: MCOM_BUILD

# affected services
services:
    NAVAPP:
        cloud:
            - navapp: 1
    SDP:
        fixed:
            host: 64.151.85.184
            port: 8080
    MCOM:
        cloud:
            - mcom: 1

# cloud server types
cloud:
    navapp:
        ram: 2GB
        image: 3456
    mcom:
        ram: 4GB
        image: 3998

# used and deployed software components
components:
    macyswar:
        version: $(MCOM_BUILD)
    catalogweb:
        version: $(CATALOG_WEB_BUILD)
        imgserver: ${navapp.SCENE7_IMG_SERVER}
        replication_enabled: false
        bdb_port: 8080

# each of these blocks (services, cloud, components, deployment)
# may be defined either locally (in-document) either externally
# (in other file). In other words, we defenitely should support
# "include" mechanism

# deployment scheme
deployment:
    mcom:
        - macyswar
    navapp:
        - catalogweb
...
